AllCops:
  Exclude:
    - "afterpay-sdk.gemspec"
    - "bin/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - "spec/**/*"
    - "Gemfile"
    - "Rakefile"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/afterpay-sdk.rb"
Naming/VariableNumber:
  Enabled: false
